### PR TITLE
[MRG+1] FIX all the examples to use the new cv classes

### PR DESCRIPTION
**Pull request by raghavrv**
@amueller @vene @jnothman Please take a look :)

### CODE REVIEW

**Comment by jnothman** [comment]
travis says no

**Comment by raghavrv** [comment]
@vene till #4252 is fixed we'll have to use 2D X (at least for the `cross_val_score` and `cross_val_predict`)

**Comment by raghavrv** [comment]
haha it should say yes now!! ;)

**Comment by vene** [comment]
Why is the 2D X comment relevant in this PR? It looks like there are test-related commits that belong in scikit-learn#4294 rather than here.

**Comment by raghavrv** [comment]
I haven't rebased this I think... That should fix it :)

**Comment by raghavrv** [comment]
fixed :)

**Comment by amueller** [comment]
this looks good.

**Comment by raghavrv** [comment]
Thanks for the review!!

**Comment by raghavrv** [comment]
@vene +1 on this??

**Comment by raghavrv** [comment]
BTW I'll merge this to `model_selection` branch (#4294) just before that gets merged...

**Pull request merged**
