### PR TITLE
[MRG] Model selection clean up old files - Reuse as much as possible from the new module(s)

### PR DESCRIPTION
**Pull request by raghavrv**
@jnothman @amueller @vene Please take a look!

This should clean up a lot.

I am not sure if I should clean up the tests.. There will be a lot of duplicated tests but I felt not removing them will ensure that we are able to import the duplicated modules from cross validation and that they work as before...

### CODE REVIEW

**Comment by amueller** [comment]
why is there a landscape bot here?! do you have some hooks on your repo?

**Comment by amueller** [comment]
ah this is a PR to your branch...

**Comment by raghavrv** [comment]
haha yes! wait I'll disable it :)

**Comment by raghavrv** [comment]
Apart from this does this LGTY?? Also @amueller? 

And importantly @GaelVaroquaux are you okay with this approach??

**Comment by amueller** [comment]
We should really first get https://github.com/scikit-learn/scikit-learn/pull/4294 in, I think.

**Pull request closed without merging**
